# Generated by Django 4.2.11 on 2024-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refapp', '0003_remove_customuser_timestamp_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
